language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../ProgrammingMethodsMatrix
  - make -j
  - ./test/test_tmatrix
notifications:
  email: false